
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tiffa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Archivo = new javax.swing.JPanel();
        jd_crearCamp = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_nombCamp = new javax.swing.JTextField();
        jcmb_tipoCamp = new javax.swing.JComboBox<>();
        jtxt_longCamp = new javax.swing.JTextField();
        jbtn_agregarCamp = new javax.swing.JButton();
        jbtn_salirCamp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist_newCamp = new javax.swing.JList<>();
        jcmb_primaria = new javax.swing.JComboBox<>();
        jtp_Principal = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_newarch = new javax.swing.JMenuItem();
        jmi_salvararch = new javax.swing.JMenuItem();
        jmi_closearch = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenuItem();
        jm_campos = new javax.swing.JMenu();
        jmi_newcampo = new javax.swing.JMenuItem();
        jmi_listarcampo = new javax.swing.JMenuItem();
        jmi_modcampo = new javax.swing.JMenuItem();
        jmi_borrarcampo = new javax.swing.JMenuItem();
        jm_registros = new javax.swing.JMenu();
        jmi_introregis = new javax.swing.JMenuItem();
        jmi_modregis = new javax.swing.JMenuItem();
        jmi_buscarregis = new javax.swing.JMenuItem();
        jmi_borrarregis = new javax.swing.JMenuItem();
        jmi_listarregis = new javax.swing.JMenuItem();
        jm_indices = new javax.swing.JMenu();
        jmi_crearind = new javax.swing.JMenuItem();
        jmi_reindex = new javax.swing.JMenuItem();
        jm_estandar = new javax.swing.JMenu();
        jmi_expexcel = new javax.swing.JMenuItem();
        jmi_expXML = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jp_ArchivoLayout = new javax.swing.GroupLayout(jp_Archivo);
        jp_Archivo.setLayout(jp_ArchivoLayout);
        jp_ArchivoLayout.setHorizontalGroup(
            jp_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jp_ArchivoLayout.setVerticalGroup(
            jp_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Nombre Campo");

        jLabel2.setText("Tipo");

        jLabel3.setText("Llave Primaria");

        jLabel4.setText("Logitud");

        jcmb_tipoCamp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entero", "Caracter", "Cadena Caracteres", "Entero con decimales" }));

        jtxt_longCamp.setName("jtxt_longCamp"); // NOI18N

        jbtn_agregarCamp.setText("Agregar");
        jbtn_agregarCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarCampActionPerformed(evt);
            }
        });

        jbtn_salirCamp.setText("Salir");
        jbtn_salirCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirCampActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jlist_newCamp);

        jcmb_primaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        javax.swing.GroupLayout jd_crearCampLayout = new javax.swing.GroupLayout(jd_crearCamp.getContentPane());
        jd_crearCamp.getContentPane().setLayout(jd_crearCampLayout);
        jd_crearCampLayout.setHorizontalGroup(
            jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearCampLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearCampLayout.createSequentialGroup()
                        .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(76, 76, 76)
                        .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_longCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxt_nombCamp)
                                .addComponent(jcmb_tipoCamp, 0, 272, Short.MAX_VALUE))
                            .addComponent(jcmb_primaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_agregarCamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_salirCamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jd_crearCampLayout.setVerticalGroup(
            jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearCampLayout.createSequentialGroup()
                .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearCampLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxt_nombCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcmb_tipoCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jtxt_longCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcmb_primaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_crearCampLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_crearCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_crearCampLayout.createSequentialGroup()
                                .addComponent(jbtn_agregarCamp)
                                .addGap(37, 37, 37)
                                .addComponent(jbtn_salirCamp)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_archivo.setText("Archivo");

        jmi_newarch.setText("Nuevo Archivo");
        jmi_newarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_newarchActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_newarch);

        jmi_salvararch.setText("Salvar Archivo");
        jmi_salvararch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salvararchActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_salvararch);

        jmi_closearch.setText("Cerrar Archivo");
        jmi_closearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_closearchActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_closearch);

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_salir);

        jMenuBar1.add(jm_archivo);

        jm_campos.setText("Campos");

        jmi_newcampo.setText("Crear  Campos");
        jmi_newcampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_newcampoActionPerformed(evt);
            }
        });
        jm_campos.add(jmi_newcampo);

        jmi_listarcampo.setText("Listar Campos");
        jm_campos.add(jmi_listarcampo);

        jmi_modcampo.setText("Modificar Campos");
        jm_campos.add(jmi_modcampo);

        jmi_borrarcampo.setText("Borrar Campos");
        jm_campos.add(jmi_borrarcampo);

        jMenuBar1.add(jm_campos);

        jm_registros.setText("Registros");
        jm_registros.setEnabled(false);

        jmi_introregis.setText("Introducir Registros");
        jm_registros.add(jmi_introregis);

        jmi_modregis.setText("Modificar Registros");
        jm_registros.add(jmi_modregis);

        jmi_buscarregis.setText("Buscar Registros");
        jm_registros.add(jmi_buscarregis);

        jmi_borrarregis.setText("Borrar Registros");
        jm_registros.add(jmi_borrarregis);

        jmi_listarregis.setText("Listar Registros");
        jm_registros.add(jmi_listarregis);

        jMenuBar1.add(jm_registros);

        jm_indices.setText("Indices");

        jmi_crearind.setText("Crear Indices");
        jm_indices.add(jmi_crearind);

        jmi_reindex.setText("Re Indexar Archivos");
        jm_indices.add(jmi_reindex);

        jMenuBar1.add(jm_indices);

        jm_estandar.setText("Estandarizacion");

        jmi_expexcel.setText("Exportar Excel");
        jm_estandar.add(jmi_expexcel);

        jmi_expXML.setText("Exportar XML con Schema");
        jm_estandar.add(jmi_expXML);

        jMenuBar1.add(jm_estandar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtp_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtp_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_newarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_newarchActionPerformed
        // TODO add your handling code here:
        JPanel p = new JPanel();
        String nombre;

        p = jp_Archivo;

        nombre = JOptionPane.showInputDialog(this, "Ingrese Nombre: ");
        metadata = nombre;
        p.setName(nombre);

        jtp_Principal.add(p);
        archivo.setNombre(nombre);
    }//GEN-LAST:event_jmi_newarchActionPerformed

    private void jmi_salvararchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salvararchActionPerformed
        // TODO add your handling code here:
        AccesoCampo cam = new AccesoCampo();
        File archive;
        try {

            archive = new File("./" + metadata + ".txt");
            for (int i = 0; i < registros.size(); i++) {
                System.out.println("Registro #" + i);
                for (int j = 0; j < campos.size(); j++) {
                    System.out.println("Campo #" + i + " :" + registros.get(i).getCampos().get(j).getContenido());
                }
            }

            archive = new File("./" + metadata + ".txt");

            cam.crearFileCampo(archive);
            cam.escribirMetadata(metadata);
            cam.escribirNumRegistros(registros);
            cam.escribirCampos(campos, metadata);
            cam.escribirRegistro(registros);
            JOptionPane.showMessageDialog(null, "Se ha guardado exitosamente!");
            
            cam.cerrar();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Pasar la informacion correspondiente a las tablas

    }//GEN-LAST:event_jmi_salvararchActionPerformed

    private void jmi_closearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_closearchActionPerformed
        // TODO add your handling code here:
        archivo = new Archivo();
        
        JPanel p = new JPanel();
        
        jtp_Principal.removeAll();
        
        registros = new ArrayList();
        campos = new ArrayList();
        
        cargado = false;
    }//GEN-LAST:event_jmi_closearchActionPerformed

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmi_salirActionPerformed

    private void jmi_newcampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_newcampoActionPerformed
        // TODO add your handling code here:
        jd_crearCamp.setModal(true);
        jd_crearCamp.pack();
        jd_crearCamp.setLocationRelativeTo(this);
        jd_crearCamp.setVisible(true);
    }//GEN-LAST:event_jmi_newcampoActionPerformed

    private void jbtn_agregarCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarCampActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = new DefaultListModel();
        try {
            Campo campo;
            String nombreCamp = jtxt_nombCamp.getText();
            String tipoCamp = jcmb_tipoCamp.getSelectedItem().toString();
            int longitud = Integer.parseInt(jtxt_longCamp.getText());
            campo = new Campo(nombreCamp,tipoCamp,longitud);
            if (jcmb_primaria.getSelectedIndex()==0) {
                campo.setPri(true);
                jcmb_primaria.setEnabled(false);
                jcmb_primaria.setSelectedIndex(1);
            }
            else{
                campo.setPri(false);
            }
            campos.add(campo);
            modelo.removeAllElements();;
            //DefaultListModel modelo1 = (DefaultListModel) jlist_newCamp.getModel();
            for (int i = 0; i < campos.size(); i++) {
                modelo.addElement(campos.get(i));
            }
            jlist_newCamp.setModel(modelo);
            
            jtxt_nombCamp.setText("");
            jtxt_longCamp.setText("");
            jcmb_tipoCamp.setSelectedIndex(0);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtn_agregarCampActionPerformed

    private void jbtn_salirCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirCampActionPerformed
        // TODO add your handling code here:
        AccesoCampo ac;
        String nombre;
        DefaultListModel modelo = new DefaultListModel();
        jm_registros.setEnabled(true);
        jd_crearCamp.setVisible(false);
        
    }//GEN-LAST:event_jbtn_salirCampActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_agregarCamp;
    private javax.swing.JButton jbtn_salirCamp;
    private javax.swing.JComboBox<String> jcmb_primaria;
    private javax.swing.JComboBox<String> jcmb_tipoCamp;
    private javax.swing.JDialog jd_crearCamp;
    private javax.swing.JList<String> jlist_newCamp;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenu jm_campos;
    private javax.swing.JMenu jm_estandar;
    private javax.swing.JMenu jm_indices;
    private javax.swing.JMenu jm_registros;
    private javax.swing.JMenuItem jmi_borrarcampo;
    private javax.swing.JMenuItem jmi_borrarregis;
    private javax.swing.JMenuItem jmi_buscarregis;
    private javax.swing.JMenuItem jmi_closearch;
    private javax.swing.JMenuItem jmi_crearind;
    private javax.swing.JMenuItem jmi_expXML;
    private javax.swing.JMenuItem jmi_expexcel;
    private javax.swing.JMenuItem jmi_introregis;
    private javax.swing.JMenuItem jmi_listarcampo;
    private javax.swing.JMenuItem jmi_listarregis;
    private javax.swing.JMenuItem jmi_modcampo;
    private javax.swing.JMenuItem jmi_modregis;
    private javax.swing.JMenuItem jmi_newarch;
    private javax.swing.JMenuItem jmi_newcampo;
    private javax.swing.JMenuItem jmi_reindex;
    private javax.swing.JMenuItem jmi_salir;
    private javax.swing.JMenuItem jmi_salvararch;
    private javax.swing.JPanel jp_Archivo;
    private javax.swing.JTabbedPane jtp_Principal;
    private javax.swing.JTextField jtxt_longCamp;
    private javax.swing.JTextField jtxt_nombCamp;
    // End of variables declaration//GEN-END:variables
    ArrayList<Campo> campos = new ArrayList();
    ArrayList<Registro> registros = new ArrayList();
    Archivo archivo = new Archivo();
    JPanel p = new JPanel();
    File archivoGuardar = null;
    String metadata = "";
    Boolean cargado=false;
}
